pull_request_rules:
  - name: Merge dependabot PRs automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - base=master
      - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      merge:
        method: merge
  - name: Merge on approval automatically
    conditions:
      - base=master
      - '#approved-reviews-by>1'
    actions:
      merge:
        method: merge
  - name: Add dependencies label when package.json is modified
    conditions:
      - files=package.json
    actions:
      label:
        add:
          - dependencies
